#!/bin/sh

# Set these paths appropriately

BIN="/home/illuminiation/of_v0.11.0_linux64gcc6_release/apps/Illumination/pos-tagging/bin"
CMD="/home/illuminiation/of_v0.11.0_linux64gcc6_release/apps/Illumination/pos-tagging/cmd"
LIB="/home/illuminiation/of_v0.11.0_linux64gcc6_release/apps/Illumination/pos-tagging/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations
PARFILE=${LIB}/greek.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

